# Generated by Django 5.2.6 on 2025-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("artisan", "Artisan"),
                    ("buyer", "Buyer"),
                    ("admin", "Admin"),
                ],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
