# Generated by Django 5.2.6 on 2025-09-22 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_artisan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdesignrequest",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_artisan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_requests_as_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "buyer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "artisan"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
