# Generated by Django 5.2.6 on 2025-09-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_customdesignrequest_artisan_and_more"),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.inventory",
            ),
        ),
    ]
