# Generated by Django 5.2.6 on 2025-10-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_product"),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdesignrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customdesignrequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="labour_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="material_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="quote_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="reference_images",
            field=models.ImageField(default=None, upload_to="reference_images/"),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("material-sourcing", "Material-sourcing"),
                    ("in-progress", "In-progress"),
                    ("completed", "Completed"),
                ],
                default="material_sourced",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ArtisanUploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="order_images/")),
                (
                    "custom_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artisan_uploads",
                        to="orders.customdesignrequest",
                    ),
                ),
            ],
        ),
    ]
