# Generated by Django 4.2.25 on 2025-10-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_customdesignrequest_is_accepted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artisanuploadimage",
            old_name="images",
            new_name="image",
        ),
    ]
