# Generated by Django 4.2.25 on 2025-10-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_rename_images_artisanuploadimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.customdesignrequest",
            ),
        ),
    ]
